export const up = ( pgm ) => {

  pgm.sql ( `
    -- ============ ACESSO ============

    CREATE TABLE "Users" 
    (
      "codUser"   INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "perfil"    VARCHAR(14)     NOT NULL,
      "user"      VARCHAR(128)    NOT NULL,
      "email"     VARCHAR(150)    NOT NULL,
      "senha"     VARCHAR(22)     NOT NULL,
      "dtCriacao" TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"  TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "isActive"  BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Users_pkey" PRIMARY KEY ("codUser")
    );
    CREATE UNIQUE INDEX "Users_email_key" ON "Users"("email");

    -- ============ LOCALIZAÇÃO ============

    CREATE TABLE "Paises" 
    (
      "codPais"   INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "pais"      VARCHAR(6)      NOT NULL,
      "sigla"     VARCHAR(3)      NOT NULL,
      "ddi"       VARCHAR(4),
      "moeda"     VARCHAR(3),
      "dtCriacao" TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"  TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"   INTEGER,
      "isActive"  BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Paises_pkey" PRIMARY KEY ("codPais")
    );
    CREATE UNIQUE INDEX "Paises_sigla_key" ON "Paises"("sigla");

    CREATE TABLE "Estados" 
    (
      "codEstado" INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codPais"   INTEGER         NOT NULL,
      "uf"        VARCHAR(2)      NOT NULL,
      "estado"    VARCHAR(22)     NOT NULL,
      "dtCriacao" TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"  TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"   INTEGER,
      "isActive"  BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Estados_pkey" PRIMARY KEY ("codEstado")
    );
    CREATE INDEX "Estados_codPais_idx" ON "Estados"("codPais");
    ALTER TABLE "Estados"
      ADD CONSTRAINT "Estados_codPais_fkey"
      FOREIGN KEY ("codPais") REFERENCES "Paises"("codPais")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    CREATE TABLE "Cidades" 
    (
      "codCidade" INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codEstado" INTEGER         NOT NULL,
      "cidade"    VARCHAR(32)     NOT NULL,
      "ddd"       VARCHAR(2),
      "dtCriacao" TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"  TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"   INTEGER,
      "isActive"  BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Cidades_pkey" PRIMARY KEY ("codCidade")
    );
    CREATE INDEX "Cidades_codEstado_idx" ON "Cidades"("codEstado");
    ALTER TABLE "Cidades"
      ADD CONSTRAINT "Cidades_codEstado_fkey"
      FOREIGN KEY ("codEstado") REFERENCES "Estados"("codEstado")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- ============ FINANCEIRO (antes de Clientes e Parceiros) ============

    CREATE TABLE "CondicaoDePagamento" 
    (
      "codCondDePag"    INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "descricao"       VARCHAR(60),
      "juroCondPag"     DECIMAL(5,2),
      "multaCondPag"    DECIMAL(5,2),
      "descontoCondPag" DECIMAL(5,2),
      "dtCriacao"       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"        TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"         INTEGER,
      "isActive"        BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "CondicaoDePagamento_pkey" PRIMARY KEY ("codCondDePag")
    );

    CREATE TABLE "FormaDePagamento" 
    (
      "codFormaDePag"    INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "formaDePag"       VARCHAR(50)     NOT NULL,
      "prazoCompensacao" INTEGER,
      "dtCriacao"        TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"         TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"          INTEGER,
      "isActive"         BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "FormaDePagamento_pkey" PRIMARY KEY ("codFormaDePag")
    );

    CREATE TABLE "Parcelas" 
    (
      "codParcela"    INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codCondDePag"  INTEGER         NOT NULL,
      "codFormaDePag" INTEGER         NOT NULL,
      "percentual"    DECIMAL(5,2)    NOT NULL,
      "numDias"       INTEGER         NOT NULL,
      "dtCriacao"     TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"      TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"       INTEGER,
      "isActive"      BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Parcelas_pkey" PRIMARY KEY ("codParcela")
    );
    CREATE INDEX "Parcelas_codCondDePag_idx"  ON "Parcelas"("codCondDePag");
    CREATE INDEX "Parcelas_codFormaDePag_idx" ON "Parcelas"("codFormaDePag");
    ALTER TABLE "Parcelas"
      ADD CONSTRAINT "Parcelas_codCondDePag_fkey"
      FOREIGN KEY ("codCondDePag") REFERENCES "CondicaoDePagamento"("codCondDePag")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "Parcelas"
      ADD CONSTRAINT "Parcelas_codFormaDePag_fkey"
      FOREIGN KEY ("codFormaDePag") REFERENCES "FormaDePagamento"("codFormaDePag")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- ============ LOGÍSTICA (antes de Transportadoras) ============

    CREATE TABLE "Veiculos" 
    (
      "codVeiculo"    INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "modeloVeiculo" VARCHAR(100),
      "marca"         VARCHAR(13),
      "codEstado"     INTEGER,
      "placaVeiculo"  VARCHAR(7)      NOT NULL,
      "placaMercoSul" VARCHAR(7),
      "codAntt"       TEXT,
      "dtCriacao"     TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"      TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"       INTEGER,
      "isActive"      BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Veiculos_pkey" PRIMARY KEY ("codVeiculo")
    );
    CREATE INDEX "Veiculos_codEstado_idx" ON "Veiculos"("codEstado");
    ALTER TABLE "Veiculos"
      ADD CONSTRAINT "Veiculos_codEstado_fkey"
      FOREIGN KEY ("codEstado") REFERENCES "Estados"("codEstado")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- ============ PARCEIROS ============

    CREATE TABLE "Fornecedores" 
    (
      "codForn"        INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codCidade"      INTEGER         NOT NULL,
      "fornecedor"     VARCHAR(128)    NOT NULL,
      "nomeFantasia"   VARCHAR(60),
      "enderecoForn"   VARCHAR(150),
      "bairroForn"     VARCHAR(100),
      "cepForn"        VARCHAR(8),
      "foneForn"       VARCHAR(15),
      "cpfCnpjForn"    VARCHAR(14),
      "inscEstSubTrib" VARCHAR(15),
      "dtCriacao"      TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"        INTEGER,
      "isActive"       BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Fornecedores_pkey" PRIMARY KEY ("codForn")
    );
    CREATE INDEX "Fornecedores_codCidade_idx" ON "Fornecedores"("codCidade");
    ALTER TABLE "Fornecedores"
      ADD CONSTRAINT "Fornecedores_codCidade_fkey"
      FOREIGN KEY ("codCidade") REFERENCES "Cidades"("codCidade")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    CREATE TABLE "Clientes" 
    (
      "codCliente"   INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codCidade"    INTEGER         NOT NULL,
      "codCondDePag" INTEGER,
      "cliente"      VARCHAR(128)    NOT NULL,
      "enderecoCl"   VARCHAR(150),
      "bairroCl"     VARCHAR(100),
      "cepCl"        VARCHAR(8),
      "foneCl"       VARCHAR(15),
      "dtCriacao"    TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"     TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"      INTEGER,
      "isActive"     BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Clientes_pkey" PRIMARY KEY ("codCliente")
    );
    CREATE INDEX "Clientes_codCidade_idx"    ON "Clientes"("codCidade");
    CREATE INDEX "Clientes_codCondDePag_idx" ON "Clientes"("codCondDePag");
    ALTER TABLE "Clientes"
      ADD CONSTRAINT "Clientes_codCidade_fkey"
      FOREIGN KEY ("codCidade") REFERENCES "Cidades"("codCidade")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "Clientes"
      ADD CONSTRAINT "Clientes_codCondDePag_fkey"
      FOREIGN KEY ("codCondDePag") REFERENCES "CondicaoDePagamento"("codCondDePag")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    CREATE TABLE "Transportadoras" 
    (
      "codTransp"      INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codCidade"      INTEGER         NOT NULL,
      "codVeiculo"     INTEGER,
      "transportadora" VARCHAR(128)    NOT NULL,
      "nomeFantasia"   VARCHAR(60),
      "tipoPessoa"     VARCHAR(8),
      "enderecoTransp" VARCHAR(35),
      "cpfCnpjTransp"  VARCHAR(14),
      "inscEstTransp"  VARCHAR(15),
      "dtCriacao"      TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"        INTEGER,
      "isActive"       BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Transportadoras_pkey" PRIMARY KEY ("codTransp")
    );
    CREATE INDEX "Transportadoras_codCidade_idx"  ON "Transportadoras"("codCidade");
    CREATE INDEX "Transportadoras_codVeiculo_idx" ON "Transportadoras"("codVeiculo");
    ALTER TABLE "Transportadoras"
      ADD CONSTRAINT "Transportadoras_codCidade_fkey"
      FOREIGN KEY ("codCidade") REFERENCES "Cidades"("codCidade")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "Transportadoras"
      ADD CONSTRAINT "Transportadoras_codVeiculo_fkey"
      FOREIGN KEY ("codVeiculo") REFERENCES "Veiculos"("codVeiculo")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- ============ CATÁLOGO ============

    CREATE TABLE "Categorias" 
    (
      "codCategoria" INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "categoria"    VARCHAR(40)     NOT NULL,
      "dtCriacao"    TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"     TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"      INTEGER,
      "isActive"     BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Categorias_pkey" PRIMARY KEY ("codCategoria")
    );

    CREATE TABLE "Produtos" 
    (
      "codProd"        INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codCategoria"   INTEGER,
      "produto"        VARCHAR(100)    NOT NULL,
      "undProduto"     VARCHAR(4),
      "pesoBruto"      DECIMAL(10,3),
      "pesoLiq"        DECIMAL(10,3),
      "saldoProd"      DECIMAL(10,3)   NOT NULL DEFAULT 0,
      "custoMedioProd" DECIMAL(10,2)   NOT NULL DEFAULT 0,
      "dtCriacao"      TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"        INTEGER,
      "isActive"       BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Produtos_pkey" PRIMARY KEY ("codProd")
    );
    CREATE INDEX "Produtos_codCategoria_idx" ON "Produtos"("codCategoria");
    ALTER TABLE "Produtos"
      ADD CONSTRAINT "Produtos_codCategoria_fkey"
      FOREIGN KEY ("codCategoria") REFERENCES "Categorias"("codCategoria")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- Associativa N:N — Produto ↔ Fornecedor (sem isActive — entidade fraca)
    CREATE TABLE "ProdutoFornecedor" (
      "codProd"   INTEGER         NOT NULL,
      "codForn"   INTEGER         NOT NULL,
      "dtCriacao" TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"  TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"   INTEGER,
      CONSTRAINT "ProdutoFornecedor_pkey" PRIMARY KEY ("codProd", "codForn")
    );
    ALTER TABLE "ProdutoFornecedor"
      ADD CONSTRAINT "ProdutoFornecedor_codProd_fkey"
      FOREIGN KEY ("codProd") REFERENCES "Produtos"("codProd")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "ProdutoFornecedor"
      ADD CONSTRAINT "ProdutoFornecedor_codForn_fkey"
      FOREIGN KEY ("codForn") REFERENCES "Fornecedores"("codForn")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- Associativa N:N — Produto ↔ Categoria (sem colunas extras — Prisma define apenas as FKs)
    CREATE TABLE "ProdutoCategoria" (
      "codProduto"   INTEGER NOT NULL,
      "codCategoria" INTEGER NOT NULL,
      CONSTRAINT "ProdutoCategoria_pkey" PRIMARY KEY ("codProduto", "codCategoria")
    );
    ALTER TABLE "ProdutoCategoria"
      ADD CONSTRAINT "ProdutoCategoria_codProduto_fkey"
      FOREIGN KEY ("codProduto") REFERENCES "Produtos"("codProd")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "ProdutoCategoria"
      ADD CONSTRAINT "ProdutoCategoria_codCategoria_fkey"
      FOREIGN KEY ("codCategoria") REFERENCES "Categorias"("codCategoria")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- ============ FISCAL ============

    -- codVeiculo é campo escalar simples (sem FK — Prisma não define @relation para ele aqui;
    -- a relação Veículos ↔ NF-e é gerida pela tabela VeiculoNfe)
    CREATE TABLE "NotasFiscaisEletronicas" 
    (
      "codNfe"            INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codFornecedor"     INTEGER,
      "codTransportadora" INTEGER,
      "codProduto"        INTEGER,
      "codVeiculo"        INTEGER,
      "modelo"            VARCHAR(9),
      "numSerie"          VARCHAR(3),
      "naturezaOp"        VARCHAR(60),
      "inscEstadualNfe"   VARCHAR(10),
      "cpfCnpjNfe"        VARCHAR(14),
      "infoCompl"         VARCHAR(2000),
      "chaveAcessoNfe"    CHAR(44),
      "fretePorConta"     VARCHAR(20),
      "dtReciboNfe"       TIMESTAMP(3),
      "dhEmiNfe"          TIMESTAMP(3),
      "dhSaiNfe"          TIMESTAMP(3),
      "dtAcessoProduto"   TIMESTAMP(3),
      "csosnProdNfe"      VARCHAR(10),
      "cfopNfe"           VARCHAR(10),
      "qtdProdNfe"        DECIMAL(10,3),
      "vlrUnProdNfe"      DECIMAL(10,2),
      "vlrDescProdNfe"    DECIMAL(10,2),
      "vlrProdNfe"        DECIMAL(10,2),
      "vlrIpiProdNfe"     DECIMAL(10,2),
      "aliqIcmsProdNfe"   DECIMAL(5,2),
      "aliqIpiProdNfe"    DECIMAL(5,2),
      "baseIcmsProdNfe"   DECIMAL(10,2),
      "calcIcmsSubs"      DECIMAL(10,2),
      "vlrIcmsSubs"       DECIMAL(10,2),
      "dtCriacao"         TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"          TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"           INTEGER,
      "isActive"          BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "NotasFiscaisEletronicas_pkey" PRIMARY KEY ("codNfe")
    );
    CREATE UNIQUE INDEX "NotasFiscaisEletronicas_chaveAcessoNfe_key"
      ON "NotasFiscaisEletronicas"("chaveAcessoNfe");
    CREATE INDEX "NotasFiscaisEletronicas_codFornecedor_idx"
      ON "NotasFiscaisEletronicas"("codFornecedor");
    CREATE INDEX "NotasFiscaisEletronicas_codTransportadora_idx"
      ON "NotasFiscaisEletronicas"("codTransportadora");
    CREATE INDEX "NotasFiscaisEletronicas_codProduto_idx"
      ON "NotasFiscaisEletronicas"("codProduto");
    ALTER TABLE "NotasFiscaisEletronicas"
      ADD CONSTRAINT "NotasFiscaisEletronicas_codFornecedor_fkey"
      FOREIGN KEY ("codFornecedor") REFERENCES "Fornecedores"("codForn")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "NotasFiscaisEletronicas"
      ADD CONSTRAINT "NotasFiscaisEletronicas_codTransportadora_fkey"
      FOREIGN KEY ("codTransportadora") REFERENCES "Transportadoras"("codTransp")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "NotasFiscaisEletronicas"
      ADD CONSTRAINT "NotasFiscaisEletronicas_codProduto_fkey"
      FOREIGN KEY ("codProduto") REFERENCES "Produtos"("codProd")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- Itens da NF-e: campos tributários por item (sem isActive — entidade fraca)
    CREATE TABLE "ProdutoNfe" 
    (
      "codNfe"          INTEGER         NOT NULL,
      "codProduto"      INTEGER         NOT NULL,
      "prodBcIcms"      DECIMAL(10,2),
      "prodCfopNfe"     VARCHAR(10),
      "prodCsosnNfe"    VARCHAR(10),
      "prodVlrUnNfe"    DECIMAL(10,2),
      "prodQtdNfe"      DECIMAL(10,3),
      "prodVlrDescNfe"  DECIMAL(10,2),
      "prodVlrIcmsNfe"  DECIMAL(10,2),
      "prodVlrIpiNfe"   DECIMAL(10,2),
      "prodAliqIcmsNfe" DECIMAL(5,2),
      "prodAliqIpiNfe"  DECIMAL(5,2),
      "dtCriacao"       TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"        TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"         INTEGER,
      CONSTRAINT "ProdutoNfe_pkey" PRIMARY KEY ("codNfe", "codProduto")
    );
    ALTER TABLE "ProdutoNfe"
      ADD CONSTRAINT "ProdutoNfe_codNfe_fkey"
      FOREIGN KEY ("codNfe") REFERENCES "NotasFiscaisEletronicas"("codNfe")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "ProdutoNfe"
      ADD CONSTRAINT "ProdutoNfe_codProduto_fkey"
      FOREIGN KEY ("codProduto") REFERENCES "Produtos"("codProd")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- Associativa N:N — Veículo ↔ NF-e (Prisma define apenas as 3 colunas, sem campos extras)
    CREATE TABLE "VeiculoNfe" 
    (
      "codNfe"     INTEGER NOT NULL,
      "codVeiculo" INTEGER NOT NULL,
      "codForn"    INTEGER,
      CONSTRAINT "VeiculoNfe_pkey" PRIMARY KEY ("codNfe", "codVeiculo")
    );
    CREATE INDEX "VeiculoNfe_codForn_idx" ON "VeiculoNfe"("codForn");
    ALTER TABLE "VeiculoNfe"
      ADD CONSTRAINT "VeiculoNfe_codNfe_fkey"
      FOREIGN KEY ("codNfe") REFERENCES "NotasFiscaisEletronicas"("codNfe")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "VeiculoNfe"
      ADD CONSTRAINT "VeiculoNfe_codVeiculo_fkey"
      FOREIGN KEY ("codVeiculo") REFERENCES "Veiculos"("codVeiculo")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "VeiculoNfe"
      ADD CONSTRAINT "VeiculoNfe_codForn_fkey"
      FOREIGN KEY ("codForn") REFERENCES "Fornecedores"("codForn")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- ============ FINANCEIRO — Contas (dependem de NFe) ============

    CREATE TABLE "ContasAPagar" 
    (
      "codContasAPag" INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codNfe"        INTEGER,
      "codFornecedor" INTEGER         NOT NULL,
      "codParcela"    INTEGER,
      "vencFatura"    TIMESTAMP(3),
      "vlrFatura"     DECIMAL(10,2),
      "dtCriacao"     TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"      TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"       INTEGER,
      "isActive"      BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "ContasAPagar_pkey" PRIMARY KEY ("codContasAPag")
    );
    CREATE INDEX "ContasAPagar_codNfe_idx"        ON "ContasAPagar"("codNfe");
    CREATE INDEX "ContasAPagar_codFornecedor_idx" ON "ContasAPagar"("codFornecedor");
    CREATE INDEX "ContasAPagar_codParcela_idx"    ON "ContasAPagar"("codParcela");
    ALTER TABLE "ContasAPagar"
      ADD CONSTRAINT "ContasAPagar_codNfe_fkey"
      FOREIGN KEY ("codNfe") REFERENCES "NotasFiscaisEletronicas"("codNfe")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "ContasAPagar"
      ADD CONSTRAINT "ContasAPagar_codFornecedor_fkey"
      FOREIGN KEY ("codFornecedor") REFERENCES "Fornecedores"("codForn")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "ContasAPagar"
      ADD CONSTRAINT "ContasAPagar_codParcela_fkey"
      FOREIGN KEY ("codParcela") REFERENCES "Parcelas"("codParcela")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    CREATE TABLE "ContasAReceber" 
    (
      "codContasARec" INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codNfe"        INTEGER,
      "codCliente"    INTEGER         NOT NULL,
      "codFormaDePag" INTEGER,
      "dtEmissao"     TIMESTAMP(3),
      "vencRecibo"    TIMESTAMP(3),
      "dtPagamento"   TIMESTAMP(3),
      "vlrRecibo"     DECIMAL(10,2),
      "dtCriacao"     TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"      TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"       INTEGER,
      "isActive"      BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "ContasAReceber_pkey" PRIMARY KEY ("codContasARec")
    );
    CREATE INDEX "ContasAReceber_codNfe_idx"        ON "ContasAReceber"("codNfe");
    CREATE INDEX "ContasAReceber_codCliente_idx"    ON "ContasAReceber"("codCliente");
    CREATE INDEX "ContasAReceber_codFormaDePag_idx" ON "ContasAReceber"("codFormaDePag");
    ALTER TABLE "ContasAReceber"
      ADD CONSTRAINT "ContasAReceber_codNfe_fkey"
      FOREIGN KEY ("codNfe") REFERENCES "NotasFiscaisEletronicas"("codNfe")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "ContasAReceber"
      ADD CONSTRAINT "ContasAReceber_codCliente_fkey"
      FOREIGN KEY ("codCliente") REFERENCES "Clientes"("codCliente")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "ContasAReceber"
      ADD CONSTRAINT "ContasAReceber_codFormaDePag_fkey"
      FOREIGN KEY ("codFormaDePag") REFERENCES "FormaDePagamento"("codFormaDePag")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- ============ COMPRAS ============

    CREATE TABLE "Compras" 
    (
      "codCompra"   INTEGER         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "codNfe"      INTEGER,
      "codForn"     INTEGER         NOT NULL,
      "codTransp"   INTEGER,
      "codCondDePag"INTEGER,
      "dtCriacao"   TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"    TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"     INTEGER,
      "isActive"    BOOLEAN         NOT NULL DEFAULT true,
      CONSTRAINT "Compras_pkey" PRIMARY KEY ("codCompra")
    );
    CREATE INDEX "Compras_codNfe_idx"       ON "Compras"("codNfe");
    CREATE INDEX "Compras_codForn_idx"      ON "Compras"("codForn");
    CREATE INDEX "Compras_codTransp_idx"    ON "Compras"("codTransp");
    CREATE INDEX "Compras_codCondDePag_idx" ON "Compras"("codCondDePag");
    ALTER TABLE "Compras"
      ADD CONSTRAINT "Compras_codNfe_fkey"
      FOREIGN KEY ("codNfe") REFERENCES "NotasFiscaisEletronicas"("codNfe")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "Compras"
      ADD CONSTRAINT "Compras_codForn_fkey"
      FOREIGN KEY ("codForn") REFERENCES "Fornecedores"("codForn")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "Compras"
      ADD CONSTRAINT "Compras_codTransp_fkey"
      FOREIGN KEY ("codTransp") REFERENCES "Transportadoras"("codTransp")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "Compras"
      ADD CONSTRAINT "Compras_codCondDePag_fkey"
      FOREIGN KEY ("codCondDePag") REFERENCES "CondicaoDePagamento"("codCondDePag")
      ON DELETE RESTRICT ON UPDATE CASCADE;

    -- Associativa N:N — Compra ↔ Produto (sem isActive — entidade fraca)
    CREATE TABLE "CompraProduto" 
    (
      "codCompra"         INTEGER         NOT NULL,
      "codProduto"        INTEGER         NOT NULL,
      "custoMedioProduto" DECIMAL(10,2),
      "dtCriacao"         TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "dtEdicao"          TIMESTAMP(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      "codUser"           INTEGER,
      CONSTRAINT "CompraProduto_pkey" PRIMARY KEY ("codCompra", "codProduto")
    );
    ALTER TABLE "CompraProduto"
      ADD CONSTRAINT "CompraProduto_codCompra_fkey"
      FOREIGN KEY ("codCompra") REFERENCES "Compras"("codCompra")
      ON DELETE RESTRICT ON UPDATE CASCADE;
    ALTER TABLE "CompraProduto"
      ADD CONSTRAINT "CompraProduto_codProduto_fkey"
      FOREIGN KEY ("codProduto") REFERENCES "Produtos"("codProd")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  ` );
};

export const down = ( pgm ) => {

  pgm.sql ( `
    DROP TABLE IF EXISTS "CompraProduto"            CASCADE;
    DROP TABLE IF EXISTS "Compras"                  CASCADE;
    DROP TABLE IF EXISTS "ContasAReceber"           CASCADE;
    DROP TABLE IF EXISTS "ContasAPagar"             CASCADE;
    DROP TABLE IF EXISTS "VeiculoNfe"               CASCADE;
    DROP TABLE IF EXISTS "ProdutoNfe"               CASCADE;
    DROP TABLE IF EXISTS "NotasFiscaisEletronicas"  CASCADE;
    DROP TABLE IF EXISTS "Parcelas"                 CASCADE;
    DROP TABLE IF EXISTS "FormaDePagamento"         CASCADE;
    DROP TABLE IF EXISTS "CondicaoDePagamento"      CASCADE;
    DROP TABLE IF EXISTS "ProdutoCategoria"         CASCADE;
    DROP TABLE IF EXISTS "ProdutoFornecedor"        CASCADE;
    DROP TABLE IF EXISTS "Produtos"                 CASCADE;
    DROP TABLE IF EXISTS "Categorias"               CASCADE;
    DROP TABLE IF EXISTS "Transportadoras"          CASCADE;
    DROP TABLE IF EXISTS "Veiculos"                 CASCADE;
    DROP TABLE IF EXISTS "Clientes"                 CASCADE;
    DROP TABLE IF EXISTS "Fornecedores"             CASCADE;
    DROP TABLE IF EXISTS "Cidades"                  CASCADE;
    DROP TABLE IF EXISTS "Estados"                  CASCADE;
    DROP TABLE IF EXISTS "Paises"                   CASCADE;
    DROP TABLE IF EXISTS "Users"                    CASCADE;
  ` );
};
