// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.Categorias */
export type CategoriasCodCategoria = number & { __brand: 'public.Categorias' };

/** Represents the table public.Categorias */
export default interface Categorias {
  codCategoria: CategoriasCodCategoria;

  categoria: string;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.Categorias */
export interface CategoriasInitializer {
  codCategoria?: CategoriasCodCategoria;

  categoria: string;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.Categorias */
export interface CategoriasMutator {
  codCategoria?: CategoriasCodCategoria;

  categoria?: string;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
