// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CidadesCodCidade } from './Cidades';
import type { CondicaoDePagamentoCodCondDePag } from './CondicaoDePagamento';

/** Identifier type for public.Clientes */
export type ClientesCodCliente = number & { __brand: 'public.Clientes' };

/** Represents the table public.Clientes */
export default interface Clientes {
  codCliente: ClientesCodCliente;

  codCidade: CidadesCodCidade;

  codCondDePag: CondicaoDePagamentoCodCondDePag | null;

  cliente: string;

  enderecoCl: string | null;

  bairroCl: string | null;

  cepCl: string | null;

  foneCl: string | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.Clientes */
export interface ClientesInitializer {
  codCliente?: ClientesCodCliente;

  codCidade: CidadesCodCidade;

  codCondDePag?: CondicaoDePagamentoCodCondDePag | null;

  cliente: string;

  enderecoCl?: string | null;

  bairroCl?: string | null;

  cepCl?: string | null;

  foneCl?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.Clientes */
export interface ClientesMutator {
  codCliente?: ClientesCodCliente;

  codCidade?: CidadesCodCidade;

  codCondDePag?: CondicaoDePagamentoCodCondDePag | null;

  cliente?: string;

  enderecoCl?: string | null;

  bairroCl?: string | null;

  cepCl?: string | null;

  foneCl?: string | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
