// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ComprasCodCompra } from './Compras';
import type { ProdutosCodProd } from './Produtos';

/** Represents the table public.CompraProduto */
export default interface CompraProduto {
  codCompra: ComprasCodCompra;

  codProduto: ProdutosCodProd;

  custoMedioProduto: string | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;
}

/** Represents the initializer for the table public.CompraProduto */
export interface CompraProdutoInitializer {
  codCompra: ComprasCodCompra;

  codProduto: ProdutosCodProd;

  custoMedioProduto?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;
}

/** Represents the mutator for the table public.CompraProduto */
export interface CompraProdutoMutator {
  codCompra?: ComprasCodCompra;

  codProduto?: ProdutosCodProd;

  custoMedioProduto?: string | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;
}
