// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { NotasFiscaisEletronicasCodNfe } from './NotasFiscaisEletronicas';
import type { FornecedoresCodForn } from './Fornecedores';
import type { TransportadorasCodTransp } from './Transportadoras';
import type { CondicaoDePagamentoCodCondDePag } from './CondicaoDePagamento';

/** Identifier type for public.Compras */
export type ComprasCodCompra = number & { __brand: 'public.Compras' };

/** Represents the table public.Compras */
export default interface Compras {
  codCompra: ComprasCodCompra;

  codNfe: NotasFiscaisEletronicasCodNfe | null;

  codForn: FornecedoresCodForn;

  codTransp: TransportadorasCodTransp | null;

  codCondDePag: CondicaoDePagamentoCodCondDePag | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.Compras */
export interface ComprasInitializer {
  codCompra?: ComprasCodCompra;

  codNfe?: NotasFiscaisEletronicasCodNfe | null;

  codForn: FornecedoresCodForn;

  codTransp?: TransportadorasCodTransp | null;

  codCondDePag?: CondicaoDePagamentoCodCondDePag | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.Compras */
export interface ComprasMutator {
  codCompra?: ComprasCodCompra;

  codNfe?: NotasFiscaisEletronicasCodNfe | null;

  codForn?: FornecedoresCodForn;

  codTransp?: TransportadorasCodTransp | null;

  codCondDePag?: CondicaoDePagamentoCodCondDePag | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
