// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.CondicaoDePagamento */
export type CondicaoDePagamentoCodCondDePag = number & { __brand: 'public.CondicaoDePagamento' };

/** Represents the table public.CondicaoDePagamento */
export default interface CondicaoDePagamento {
  codCondDePag: CondicaoDePagamentoCodCondDePag;

  descricao: string | null;

  juroCondPag: string | null;

  multaCondPag: string | null;

  descontoCondPag: string | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.CondicaoDePagamento */
export interface CondicaoDePagamentoInitializer {
  codCondDePag?: CondicaoDePagamentoCodCondDePag;

  descricao?: string | null;

  juroCondPag?: string | null;

  multaCondPag?: string | null;

  descontoCondPag?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.CondicaoDePagamento */
export interface CondicaoDePagamentoMutator {
  codCondDePag?: CondicaoDePagamentoCodCondDePag;

  descricao?: string | null;

  juroCondPag?: string | null;

  multaCondPag?: string | null;

  descontoCondPag?: string | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
