// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { NotasFiscaisEletronicasCodNfe } from './NotasFiscaisEletronicas';
import type { ClientesCodCliente } from './Clientes';
import type { FormaDePagamentoCodFormaDePag } from './FormaDePagamento';

/** Identifier type for public.ContasAReceber */
export type ContasAReceberCodContasARec = number & { __brand: 'public.ContasAReceber' };

/** Represents the table public.ContasAReceber */
export default interface ContasAReceber {
  codContasARec: ContasAReceberCodContasARec;

  codNfe: NotasFiscaisEletronicasCodNfe | null;

  codCliente: ClientesCodCliente;

  codFormaDePag: FormaDePagamentoCodFormaDePag | null;

  dtEmissao: Date | null;

  vencRecibo: Date | null;

  dtPagamento: Date | null;

  vlrRecibo: string | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.ContasAReceber */
export interface ContasAReceberInitializer {
  codContasARec?: ContasAReceberCodContasARec;

  codNfe?: NotasFiscaisEletronicasCodNfe | null;

  codCliente: ClientesCodCliente;

  codFormaDePag?: FormaDePagamentoCodFormaDePag | null;

  dtEmissao?: Date | null;

  vencRecibo?: Date | null;

  dtPagamento?: Date | null;

  vlrRecibo?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.ContasAReceber */
export interface ContasAReceberMutator {
  codContasARec?: ContasAReceberCodContasARec;

  codNfe?: NotasFiscaisEletronicasCodNfe | null;

  codCliente?: ClientesCodCliente;

  codFormaDePag?: FormaDePagamentoCodFormaDePag | null;

  dtEmissao?: Date | null;

  vencRecibo?: Date | null;

  dtPagamento?: Date | null;

  vlrRecibo?: string | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
