// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { NotasFiscaisEletronicasCodNfe } from './NotasFiscaisEletronicas';
import type { FornecedoresCodForn } from './Fornecedores';
import type { ParcelasCodParcela } from './Parcelas';

/** Identifier type for public.ContasAPagar */
export type ContasAPagarCodContasAPag = number & { __brand: 'public.ContasAPagar' };

/** Represents the table public.ContasAPagar */
export default interface ContasAPagar {
  codContasAPag: ContasAPagarCodContasAPag;

  codNfe: NotasFiscaisEletronicasCodNfe | null;

  codFornecedor: FornecedoresCodForn;

  codParcela: ParcelasCodParcela | null;

  vencFatura: Date | null;

  vlrFatura: string | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.ContasAPagar */
export interface ContasAPagarInitializer {
  codContasAPag?: ContasAPagarCodContasAPag;

  codNfe?: NotasFiscaisEletronicasCodNfe | null;

  codFornecedor: FornecedoresCodForn;

  codParcela?: ParcelasCodParcela | null;

  vencFatura?: Date | null;

  vlrFatura?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.ContasAPagar */
export interface ContasAPagarMutator {
  codContasAPag?: ContasAPagarCodContasAPag;

  codNfe?: NotasFiscaisEletronicasCodNfe | null;

  codFornecedor?: FornecedoresCodForn;

  codParcela?: ParcelasCodParcela | null;

  vencFatura?: Date | null;

  vlrFatura?: string | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
