// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.FormaDePagamento */
export type FormaDePagamentoCodFormaDePag = number & { __brand: 'public.FormaDePagamento' };

/** Represents the table public.FormaDePagamento */
export default interface FormaDePagamento {
  codFormaDePag: FormaDePagamentoCodFormaDePag;

  formaDePag: string;

  prazoCompensacao: number | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.FormaDePagamento */
export interface FormaDePagamentoInitializer {
  codFormaDePag?: FormaDePagamentoCodFormaDePag;

  formaDePag: string;

  prazoCompensacao?: number | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.FormaDePagamento */
export interface FormaDePagamentoMutator {
  codFormaDePag?: FormaDePagamentoCodFormaDePag;

  formaDePag?: string;

  prazoCompensacao?: number | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
