// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CidadesCodCidade } from './Cidades';

/** Identifier type for public.Fornecedores */
export type FornecedoresCodForn = number & { __brand: 'public.Fornecedores' };

/** Represents the table public.Fornecedores */
export default interface Fornecedores {
  codForn: FornecedoresCodForn;

  codCidade: CidadesCodCidade;

  fornecedor: string;

  nomeFantasia: string | null;

  enderecoForn: string | null;

  bairroForn: string | null;

  cepForn: string | null;

  foneForn: string | null;

  cpfCnpjForn: string | null;

  inscEstSubTrib: string | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.Fornecedores */
export interface FornecedoresInitializer {
  codForn?: FornecedoresCodForn;

  codCidade: CidadesCodCidade;

  fornecedor: string;

  nomeFantasia?: string | null;

  enderecoForn?: string | null;

  bairroForn?: string | null;

  cepForn?: string | null;

  foneForn?: string | null;

  cpfCnpjForn?: string | null;

  inscEstSubTrib?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.Fornecedores */
export interface FornecedoresMutator {
  codForn?: FornecedoresCodForn;

  codCidade?: CidadesCodCidade;

  fornecedor?: string;

  nomeFantasia?: string | null;

  enderecoForn?: string | null;

  bairroForn?: string | null;

  cepForn?: string | null;

  foneForn?: string | null;

  cpfCnpjForn?: string | null;

  inscEstSubTrib?: string | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
