// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { FornecedoresCodForn } from './Fornecedores';
import type { TransportadorasCodTransp } from './Transportadoras';
import type { ProdutosCodProd } from './Produtos';

/** Identifier type for public.NotasFiscaisEletronicas */
export type NotasFiscaisEletronicasCodNfe = number & { __brand: 'public.NotasFiscaisEletronicas' };

/** Represents the table public.NotasFiscaisEletronicas */
export default interface NotasFiscaisEletronicas {
  codNfe: NotasFiscaisEletronicasCodNfe;

  codFornecedor: FornecedoresCodForn | null;

  codTransportadora: TransportadorasCodTransp | null;

  codProduto: ProdutosCodProd | null;

  codVeiculo: number | null;

  modelo: string | null;

  numSerie: string | null;

  naturezaOp: string | null;

  inscEstadualNfe: string | null;

  cpfCnpjNfe: string | null;

  infoCompl: string | null;

  chaveAcessoNfe: string | null;

  fretePorConta: string | null;

  dtReciboNfe: Date | null;

  dhEmiNfe: Date | null;

  dhSaiNfe: Date | null;

  dtAcessoProduto: Date | null;

  csosnProdNfe: string | null;

  cfopNfe: string | null;

  qtdProdNfe: string | null;

  vlrUnProdNfe: string | null;

  vlrDescProdNfe: string | null;

  vlrProdNfe: string | null;

  vlrIpiProdNfe: string | null;

  aliqIcmsProdNfe: string | null;

  aliqIpiProdNfe: string | null;

  baseIcmsProdNfe: string | null;

  calcIcmsSubs: string | null;

  vlrIcmsSubs: string | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.NotasFiscaisEletronicas */
export interface NotasFiscaisEletronicasInitializer {
  codNfe?: NotasFiscaisEletronicasCodNfe;

  codFornecedor?: FornecedoresCodForn | null;

  codTransportadora?: TransportadorasCodTransp | null;

  codProduto?: ProdutosCodProd | null;

  codVeiculo?: number | null;

  modelo?: string | null;

  numSerie?: string | null;

  naturezaOp?: string | null;

  inscEstadualNfe?: string | null;

  cpfCnpjNfe?: string | null;

  infoCompl?: string | null;

  chaveAcessoNfe?: string | null;

  fretePorConta?: string | null;

  dtReciboNfe?: Date | null;

  dhEmiNfe?: Date | null;

  dhSaiNfe?: Date | null;

  dtAcessoProduto?: Date | null;

  csosnProdNfe?: string | null;

  cfopNfe?: string | null;

  qtdProdNfe?: string | null;

  vlrUnProdNfe?: string | null;

  vlrDescProdNfe?: string | null;

  vlrProdNfe?: string | null;

  vlrIpiProdNfe?: string | null;

  aliqIcmsProdNfe?: string | null;

  aliqIpiProdNfe?: string | null;

  baseIcmsProdNfe?: string | null;

  calcIcmsSubs?: string | null;

  vlrIcmsSubs?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.NotasFiscaisEletronicas */
export interface NotasFiscaisEletronicasMutator {
  codNfe?: NotasFiscaisEletronicasCodNfe;

  codFornecedor?: FornecedoresCodForn | null;

  codTransportadora?: TransportadorasCodTransp | null;

  codProduto?: ProdutosCodProd | null;

  codVeiculo?: number | null;

  modelo?: string | null;

  numSerie?: string | null;

  naturezaOp?: string | null;

  inscEstadualNfe?: string | null;

  cpfCnpjNfe?: string | null;

  infoCompl?: string | null;

  chaveAcessoNfe?: string | null;

  fretePorConta?: string | null;

  dtReciboNfe?: Date | null;

  dhEmiNfe?: Date | null;

  dhSaiNfe?: Date | null;

  dtAcessoProduto?: Date | null;

  csosnProdNfe?: string | null;

  cfopNfe?: string | null;

  qtdProdNfe?: string | null;

  vlrUnProdNfe?: string | null;

  vlrDescProdNfe?: string | null;

  vlrProdNfe?: string | null;

  vlrIpiProdNfe?: string | null;

  aliqIcmsProdNfe?: string | null;

  aliqIpiProdNfe?: string | null;

  baseIcmsProdNfe?: string | null;

  calcIcmsSubs?: string | null;

  vlrIcmsSubs?: string | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
