// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CondicaoDePagamentoCodCondDePag } from './CondicaoDePagamento';
import type { FormaDePagamentoCodFormaDePag } from './FormaDePagamento';

/** Identifier type for public.Parcelas */
export type ParcelasCodParcela = number & { __brand: 'public.Parcelas' };

/** Represents the table public.Parcelas */
export default interface Parcelas {
  codParcela: ParcelasCodParcela;

  codCondDePag: CondicaoDePagamentoCodCondDePag;

  codFormaDePag: FormaDePagamentoCodFormaDePag;

  percentual: string;

  numDias: number;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.Parcelas */
export interface ParcelasInitializer {
  codParcela?: ParcelasCodParcela;

  codCondDePag: CondicaoDePagamentoCodCondDePag;

  codFormaDePag: FormaDePagamentoCodFormaDePag;

  percentual: string;

  numDias: number;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.Parcelas */
export interface ParcelasMutator {
  codParcela?: ParcelasCodParcela;

  codCondDePag?: CondicaoDePagamentoCodCondDePag;

  codFormaDePag?: FormaDePagamentoCodFormaDePag;

  percentual?: string;

  numDias?: number;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
