// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProdutosCodProd } from './Produtos';
import type { FornecedoresCodForn } from './Fornecedores';

/** Represents the table public.ProdutoFornecedor */
export default interface ProdutoFornecedor {
  codProd: ProdutosCodProd;

  codForn: FornecedoresCodForn;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;
}

/** Represents the initializer for the table public.ProdutoFornecedor */
export interface ProdutoFornecedorInitializer {
  codProd: ProdutosCodProd;

  codForn: FornecedoresCodForn;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;
}

/** Represents the mutator for the table public.ProdutoFornecedor */
export interface ProdutoFornecedorMutator {
  codProd?: ProdutosCodProd;

  codForn?: FornecedoresCodForn;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;
}
