// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ProdutosCodProd } from './Produtos';
import type { CategoriasCodCategoria } from './Categorias';

/** Represents the table public.ProdutoCategoria */
export default interface ProdutoCategoria {
  codProduto: ProdutosCodProd;

  codCategoria: CategoriasCodCategoria;
}

/** Represents the initializer for the table public.ProdutoCategoria */
export interface ProdutoCategoriaInitializer {
  codProduto: ProdutosCodProd;

  codCategoria: CategoriasCodCategoria;
}

/** Represents the mutator for the table public.ProdutoCategoria */
export interface ProdutoCategoriaMutator {
  codProduto?: ProdutosCodProd;

  codCategoria?: CategoriasCodCategoria;
}
