// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CategoriasCodCategoria } from './Categorias';

/** Identifier type for public.Produtos */
export type ProdutosCodProd = number & { __brand: 'public.Produtos' };

/** Represents the table public.Produtos */
export default interface Produtos {
  codProd: ProdutosCodProd;

  codCategoria: CategoriasCodCategoria | null;

  produto: string;

  undProduto: string | null;

  pesoBruto: string | null;

  pesoLiq: string | null;

  saldoProd: string;

  custoMedioProd: string;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.Produtos */
export interface ProdutosInitializer {
  codProd?: ProdutosCodProd;

  codCategoria?: CategoriasCodCategoria | null;

  produto: string;

  undProduto?: string | null;

  pesoBruto?: string | null;

  pesoLiq?: string | null;

  /** Default value: 0 */
  saldoProd?: string;

  /** Default value: 0 */
  custoMedioProd?: string;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.Produtos */
export interface ProdutosMutator {
  codProd?: ProdutosCodProd;

  codCategoria?: CategoriasCodCategoria | null;

  produto?: string;

  undProduto?: string | null;

  pesoBruto?: string | null;

  pesoLiq?: string | null;

  saldoProd?: string;

  custoMedioProd?: string;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
