// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { NotasFiscaisEletronicasCodNfe } from './NotasFiscaisEletronicas';
import type { ProdutosCodProd } from './Produtos';

/** Represents the table public.ProdutoNfe */
export default interface ProdutoNfe {
  codNfe: NotasFiscaisEletronicasCodNfe;

  codProduto: ProdutosCodProd;

  prodBcIcms: string | null;

  prodCfopNfe: string | null;

  prodCsosnNfe: string | null;

  prodVlrUnNfe: string | null;

  prodQtdNfe: string | null;

  prodVlrDescNfe: string | null;

  prodVlrIcmsNfe: string | null;

  prodVlrIpiNfe: string | null;

  prodAliqIcmsNfe: string | null;

  prodAliqIpiNfe: string | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;
}

/** Represents the initializer for the table public.ProdutoNfe */
export interface ProdutoNfeInitializer {
  codNfe: NotasFiscaisEletronicasCodNfe;

  codProduto: ProdutosCodProd;

  prodBcIcms?: string | null;

  prodCfopNfe?: string | null;

  prodCsosnNfe?: string | null;

  prodVlrUnNfe?: string | null;

  prodQtdNfe?: string | null;

  prodVlrDescNfe?: string | null;

  prodVlrIcmsNfe?: string | null;

  prodVlrIpiNfe?: string | null;

  prodAliqIcmsNfe?: string | null;

  prodAliqIpiNfe?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;
}

/** Represents the mutator for the table public.ProdutoNfe */
export interface ProdutoNfeMutator {
  codNfe?: NotasFiscaisEletronicasCodNfe;

  codProduto?: ProdutosCodProd;

  prodBcIcms?: string | null;

  prodCfopNfe?: string | null;

  prodCsosnNfe?: string | null;

  prodVlrUnNfe?: string | null;

  prodQtdNfe?: string | null;

  prodVlrDescNfe?: string | null;

  prodVlrIcmsNfe?: string | null;

  prodVlrIpiNfe?: string | null;

  prodAliqIcmsNfe?: string | null;

  prodAliqIpiNfe?: string | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;
}
