// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { CidadesCodCidade } from './Cidades';
import type { VeiculosCodVeiculo } from './Veiculos';

/** Identifier type for public.Transportadoras */
export type TransportadorasCodTransp = number & { __brand: 'public.Transportadoras' };

/** Represents the table public.Transportadoras */
export default interface Transportadoras {
  codTransp: TransportadorasCodTransp;

  codCidade: CidadesCodCidade;

  codVeiculo: VeiculosCodVeiculo | null;

  transportadora: string;

  nomeFantasia: string | null;

  tipoPessoa: string | null;

  enderecoTransp: string | null;

  cpfCnpjTransp: string | null;

  inscEstTransp: string | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.Transportadoras */
export interface TransportadorasInitializer {
  codTransp?: TransportadorasCodTransp;

  codCidade: CidadesCodCidade;

  codVeiculo?: VeiculosCodVeiculo | null;

  transportadora: string;

  nomeFantasia?: string | null;

  tipoPessoa?: string | null;

  enderecoTransp?: string | null;

  cpfCnpjTransp?: string | null;

  inscEstTransp?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.Transportadoras */
export interface TransportadorasMutator {
  codTransp?: TransportadorasCodTransp;

  codCidade?: CidadesCodCidade;

  codVeiculo?: VeiculosCodVeiculo | null;

  transportadora?: string;

  nomeFantasia?: string | null;

  tipoPessoa?: string | null;

  enderecoTransp?: string | null;

  cpfCnpjTransp?: string | null;

  inscEstTransp?: string | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
