// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.Users */
export type UsersCodUser = number & { __brand: 'public.Users' };

/** Represents the table public.Users */
export default interface Users {
  codUser: UsersCodUser;

  perfil: string;

  user: string;

  email: string;

  senha: string;

  dtCriacao: Date;

  dtEdicao: Date;

  isActive: boolean;
}

/** Represents the initializer for the table public.Users */
export interface UsersInitializer {
  codUser?: UsersCodUser;

  perfil: string;

  user: string;

  email: string;

  senha: string;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.Users */
export interface UsersMutator {
  codUser?: UsersCodUser;

  perfil?: string;

  user?: string;

  email?: string;

  senha?: string;

  dtCriacao?: Date;

  dtEdicao?: Date;

  isActive?: boolean;
}
