// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { NotasFiscaisEletronicasCodNfe } from './NotasFiscaisEletronicas';
import type { VeiculosCodVeiculo } from './Veiculos';
import type { FornecedoresCodForn } from './Fornecedores';

/** Represents the table public.VeiculoNfe */
export default interface VeiculoNfe {
  codNfe: NotasFiscaisEletronicasCodNfe;

  codVeiculo: VeiculosCodVeiculo;

  codForn: FornecedoresCodForn | null;
}

/** Represents the initializer for the table public.VeiculoNfe */
export interface VeiculoNfeInitializer {
  codNfe: NotasFiscaisEletronicasCodNfe;

  codVeiculo: VeiculosCodVeiculo;

  codForn?: FornecedoresCodForn | null;
}

/** Represents the mutator for the table public.VeiculoNfe */
export interface VeiculoNfeMutator {
  codNfe?: NotasFiscaisEletronicasCodNfe;

  codVeiculo?: VeiculosCodVeiculo;

  codForn?: FornecedoresCodForn | null;
}
