// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { EstadosCodEstado } from './Estados';

/** Identifier type for public.Veiculos */
export type VeiculosCodVeiculo = number & { __brand: 'public.Veiculos' };

/** Represents the table public.Veiculos */
export default interface Veiculos {
  codVeiculo: VeiculosCodVeiculo;

  modeloVeiculo: string | null;

  marca: string | null;

  codEstado: EstadosCodEstado | null;

  placaVeiculo: string;

  placaMercoSul: string | null;

  codAntt: string | null;

  dtCriacao: Date;

  dtEdicao: Date;

  codUser: number | null;

  isActive: boolean;
}

/** Represents the initializer for the table public.Veiculos */
export interface VeiculosInitializer {
  codVeiculo?: VeiculosCodVeiculo;

  modeloVeiculo?: string | null;

  marca?: string | null;

  codEstado?: EstadosCodEstado | null;

  placaVeiculo: string;

  placaMercoSul?: string | null;

  codAntt?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  dtCriacao?: Date;

  /** Default value: CURRENT_TIMESTAMP */
  dtEdicao?: Date;

  codUser?: number | null;

  /** Default value: true */
  isActive?: boolean;
}

/** Represents the mutator for the table public.Veiculos */
export interface VeiculosMutator {
  codVeiculo?: VeiculosCodVeiculo;

  modeloVeiculo?: string | null;

  marca?: string | null;

  codEstado?: EstadosCodEstado | null;

  placaVeiculo?: string;

  placaMercoSul?: string | null;

  codAntt?: string | null;

  dtCriacao?: Date;

  dtEdicao?: Date;

  codUser?: number | null;

  isActive?: boolean;
}
